# Generated by Django 5.2.5 on 2025-08-16 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="部門名稱"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="部門描述"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="策略名稱"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="策略描述")),
                (
                    "waiting_period_amount",
                    models.PositiveIntegerField(default=0, verbose_name="等待期數量"),
                ),
                (
                    "waiting_period_unit",
                    models.CharField(
                        choices=[("DAYS", "天"), ("MONTHS", "個月")],
                        default="DAYS",
                        max_length=10,
                        verbose_name="等待期單位",
                    ),
                ),
                (
                    "accrual_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "每日"),
                            ("WEEKLY", "每週"),
                            ("MONTHLY", "每月"),
                            ("YEARLY", "每年"),
                        ],
                        default="YEARLY",
                        max_length=10,
                        verbose_name="增加頻率",
                    ),
                ),
                (
                    "accrual_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=12,
                        max_digits=5,
                        verbose_name="每次增加的數量",
                    ),
                ),
                (
                    "accrual_unit",
                    models.CharField(
                        choices=[("HOURS", "小時"), ("DAYS", "天")],
                        default="DAYS",
                        max_length=10,
                        verbose_name="單位",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="假別名稱"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OnboardingChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="清單樣板名稱")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("tasks", models.TextField(verbose_name="任務列表 (每行一項)")),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="職位名稱"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="職位描述"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="假期名稱")),
                ("date", models.DateField(unique=True, verbose_name="日期")),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="ReviewCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="評估週期名稱")),
                ("start_date", models.DateField(verbose_name="開始日期")),
                ("end_date", models.DateField(verbose_name="結束日期")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否啟用"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_host",
                    models.CharField(
                        default="smtp.gmail.com",
                        max_length=255,
                        verbose_name="郵件主機 (Host)",
                    ),
                ),
                (
                    "email_port",
                    models.PositiveIntegerField(
                        default=587, verbose_name="郵件端口 (Port)"
                    ),
                ),
                (
                    "email_use_tls",
                    models.BooleanField(default=True, verbose_name="使用 TLS"),
                ),
                (
                    "email_host_user",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="發信人 Email"
                    ),
                ),
                (
                    "email_host_password",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="發信人密碼 (應用程式密碼)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="班表名稱"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
            ],
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="公告標題")),
                ("content", models.TextField(verbose_name="公告內容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="發布時間"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="是否發布"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="發布者",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="員工編號"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, verbose_name="電話"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Male", "男性"),
                            ("Female", "女性"),
                            ("Other", "其他"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="性別",
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="入職日期")),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "在職"), ("Inactive", "離職")],
                        default="Active",
                        max_length=10,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "annual_leave_balance_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="年假剩餘時數",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.department",
                        verbose_name="所屬部門",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager_of",
                        to="core.employee",
                        verbose_name="直屬主管",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="登入帳號",
                    ),
                ),
                (
                    "leave_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.leavepolicy",
                        verbose_name="年假策略",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.position",
                        verbose_name="擔任職位",
                    ),
                ),
                (
                    "work_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.workschedule",
                        verbose_name="預設班表",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="文件標題")),
                (
                    "file",
                    models.FileField(
                        upload_to="employee_documents/", verbose_name="文件"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上傳時間"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.employee",
                        verbose_name="所屬員工",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_description",
                    models.CharField(max_length=255, verbose_name="任務描述"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="是否完成"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="截止日期"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_tasks",
                        to="core.employee",
                        verbose_name="所屬員工",
                    ),
                ),
            ],
            options={
                "ordering": ["is_completed", "id"],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalanceAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours_changed", models.DecimalField(decimal_places=2, max_digits=5)),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.employee"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField(verbose_name="開始時間")),
                ("end_datetime", models.DateTimeField(verbose_name="結束時間")),
                ("reason", models.TextField(verbose_name="事由")),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="總時數 (小時)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "待審核"),
                            ("Approved", "已批准"),
                            ("Rejected", "已拒絕"),
                        ],
                        default="Pending",
                        max_length=10,
                        verbose_name="審核狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申請時間"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.employee",
                        verbose_name="申請員工",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.leavetype",
                        verbose_name="假別",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OvertimeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="加班日期")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="加班時數"
                    ),
                ),
                ("reason", models.TextField(verbose_name="加班事由")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "待審核"),
                            ("Approved", "已批准"),
                            ("Rejected", "已拒絕"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.employee"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_self_assessment",
                    models.TextField(blank=True, null=True, verbose_name="員工自評"),
                ),
                (
                    "manager_assessment",
                    models.TextField(blank=True, null=True, verbose_name="經理評語"),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - 不符合期望"),
                            (2, "2 - 需改進"),
                            (3, "3 - 符合期望"),
                            (4, "4 - 超越期望"),
                            (5, "5 - 表現卓越"),
                        ],
                        null=True,
                        verbose_name="總體評分",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="Pending", max_length=20, verbose_name="狀態"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.employee",
                        verbose_name="受評員工",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.reviewcycle",
                        verbose_name="評估週期",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "cycle")},
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="目標描述")),
                (
                    "is_achieved",
                    models.BooleanField(default=False, verbose_name="是否達成"),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="core.performancereview",
                        verbose_name="所屬評估",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicyRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "years_of_service",
                    models.PositiveIntegerField(verbose_name="服務年資滿 (年)"),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[("ADD", "增加固定值"), ("SET", "設定為新總數")],
                        default="ADD",
                        max_length=20,
                        verbose_name="規則類型",
                    ),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="調整的數量 (小時/天)",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="core.leavepolicy",
                        verbose_name="所屬策略",
                    ),
                ),
            ],
            options={
                "ordering": ["years_of_service"],
            },
        ),
        migrations.CreateModel(
            name="DutyShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("start_time", models.TimeField(verbose_name="上班時間")),
                ("end_time", models.TimeField(verbose_name="下班時間")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "星期一"),
                            (1, "星期二"),
                            (2, "星期三"),
                            (3, "星期四"),
                            (4, "星期五"),
                            (5, "星期六"),
                            (6, "星期日"),
                        ],
                        verbose_name="星期幾",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="上班時間")),
                ("end_time", models.TimeField(verbose_name="下班時間")),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="core.workschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week"],
                "unique_together": {("schedule", "day_of_week")},
            },
        ),
    ]
