# Generated by Django 5.2.5 on 2025-08-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="compensatory_leave_eligible_after_months",
            field=models.PositiveIntegerField(
                default=3, verbose_name="補假福利等待期 (月)"
            ),
        ),
    ]
