# Generated by Django 5.2.5 on 2025-08-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_employee_compensatory_leave_eligible_after_months"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="compensatory_leave_balance_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=7,
                verbose_name="補休餘額 (小時)",
            ),
        ),
    ]
