# Generated by Django 5.2.5 on 2025-08-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_employee_compensatory_leave_balance_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavepolicy",
            name="allow_carry_over",
            field=models.BooleanField(default=False, verbose_name="允許結轉未使用假期"),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="fiscal_year_start_month",
            field=models.IntegerField(
                choices=[
                    (1, "1月"),
                    (2, "2月"),
                    (3, "3月"),
                    (4, "4月"),
                    (5, "5月"),
                    (6, "6月"),
                    (7, "7月"),
                    (8, "8月"),
                    (9, "9月"),
                    (10, "10月"),
                    (11, "11月"),
                    (12, "12月"),
                ],
                default=1,
                verbose_name="假期年度起始月份",
            ),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="max_carry_over_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="最大可結轉數量"
            ),
        ),
    ]
