# Generated by Django 5.2.5 on 2025-08-16 15:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_leavepolicy_allow_carry_over_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="樣板名稱")),
                ("body", ckeditor.fields.RichTextField(verbose_name="樣板內容")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="company_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos/", verbose_name="公司 Logo"
            ),
        ),
    ]
