# Generated by Django 5.2.5 on 2025-08-16 17:45

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_contracttemplate_siteconfiguration_company_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="名字")),
                ("last_name", models.CharField(max_length=100, verbose_name="姓氏")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="電話"),
                ),
                (
                    "resume",
                    models.FileField(upload_to="resumes/", verbose_name="履歷檔案"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="職位名稱")),
                ("description", ckeditor.fields.RichTextField(verbose_name="職位描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "草稿"),
                            ("Open", "開放中"),
                            ("Closed", "已關閉"),
                        ],
                        default="Draft",
                        max_length=10,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.department",
                        verbose_name="所屬部門",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Applied", "已應徵"),
                            ("Screening", "篩選中"),
                            ("Interview", "面試"),
                            ("Offered", "已提供 Offer"),
                            ("Hired", "已錄用"),
                            ("Rejected", "未錄取"),
                        ],
                        default="Applied",
                        max_length=20,
                        verbose_name="應徵狀態",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="應徵時間"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="內部備註")),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.candidate",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="core.jobopening",
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "candidate")},
            },
        ),
    ]
