# Generated by Django 5.2.5 on 2025-08-16 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_candidate_jobopening_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="allowed_ip_addresses",
            field=models.TextField(
                blank=True,
                help_text="請輸入公司允許打卡的 IP 位址，多個位址請用逗號分隔 (例如: 192.168.1.100, 203.0.113.5)",
                verbose_name="公司允許的 IP 位址",
            ),
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clock_in", models.DateTimeField(verbose_name="上班打卡時間")),
                (
                    "clock_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下班打卡時間"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="打卡 IP 位址"
                    ),
                ),
                (
                    "is_manual_entry",
                    models.BooleanField(default=False, verbose_name="是否為手動補登"),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="備註 (手動補登)"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="core.employee",
                        verbose_name="員工",
                    ),
                ),
            ],
            options={
                "ordering": ["-clock_in"],
            },
        ),
    ]
