# Generated by Django 5.2.5 on 2025-08-17 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_siteconfiguration_allowed_ip_addresses_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalaryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="生效日期")),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="基本薪資"
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        choices=[
                            ("New Hire", "新進人員"),
                            ("Promotion", "晉升"),
                            ("Annual Review", "年度調薪"),
                            ("Market Adjustment", "市場調整"),
                            ("Other", "其他"),
                        ],
                        max_length=50,
                        verbose_name="變動原因",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備註")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_history",
                        to="core.employee",
                        verbose_name="員工",
                    ),
                ),
            ],
            options={
                "verbose_name": "薪資歷史",
                "verbose_name_plural": "薪資歷史",
                "ordering": ["-effective_date", "-created_at"],
            },
        ),
    ]
