# Generated by Django 5.2.5 on 2025-08-17 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_salaryhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField(verbose_name="月份")),
                ("year", models.IntegerField(verbose_name="年份")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "草稿"),
                            ("Generated", "已生成"),
                            ("Paid", "已支付"),
                        ],
                        default="Draft",
                        max_length=10,
                        verbose_name="狀態",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "發薪週期",
                "verbose_name_plural": "發薪週期",
                "ordering": ["-year", "-month"],
                "unique_together": {("month", "year")},
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="應發薪資 (Gross)",
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="總扣款",
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="實發薪資 (Net)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="core.employee",
                        verbose_name="員工",
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="core.payrollrun",
                        verbose_name="發薪週期",
                    ),
                ),
            ],
            options={
                "verbose_name": "薪資單",
                "verbose_name_plural": "薪資單",
                "unique_together": {("payroll_run", "employee")},
            },
        ),
        migrations.CreateModel(
            name="PayslipItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("Earning", "收入"), ("Deduction", "扣款")],
                        max_length=10,
                        verbose_name="項目類型",
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="描述")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="金額"
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.payslip",
                    ),
                ),
            ],
        ),
    ]
