# Generated by Django 5.2.5 on 2025-08-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_payrollrun_payslip_payslipitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="epf_employee_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.11,
                max_digits=5,
                verbose_name="員工 EPF 費率 (例如 0.11)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="epf_employer_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.13,
                max_digits=5,
                verbose_name="僱主 EPF 費率 (例如 0.13)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="socso_employee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=19.75,
                max_digits=7,
                verbose_name="員工 SOCSO 金額 (固定值)",
            ),
        ),
    ]
