# Generated by Django 5.2.5 on 2025-08-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_siteconfiguration_epf_employee_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "epf_employee_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.11,
                        max_digits=5,
                        verbose_name="員工 EPF 費率 (例如 0.11)",
                    ),
                ),
                (
                    "epf_employer_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.13,
                        max_digits=5,
                        verbose_name="僱主 EPF 費率 (例如 0.13)",
                    ),
                ),
                (
                    "socso_employee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=19.75,
                        max_digits=7,
                        verbose_name="員工 SOCSO 金額 (固定值)",
                    ),
                ),
            ],
            options={
                "verbose_name": "薪資組態",
                "verbose_name_plural": "薪資組態",
            },
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="epf_employee_rate",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="epf_employer_rate",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="socso_employee_amount",
        ),
    ]
