# Generated by Django 5.2.5 on 2025-08-17 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_payrollconfiguration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="annual_leave_balance_hours",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="compensatory_leave_eligible_after_months",
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="剩餘時數",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="core.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.leavetype"
                    ),
                ),
            ],
            options={
                "verbose_name": "假期餘額",
                "verbose_name_plural": "假期餘額",
                "unique_together": {("employee", "leave_type")},
            },
        ),
    ]
