# Generated by Django 5.2.5 on 2025-08-18 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_employee_annual_leave_balance_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavebalanceadjustment",
            name="leave_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.leavetype",
                verbose_name="假期類型",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="leavebalanceadjustment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
        ),
        migrations.AlterField(
            model_name="leavebalanceadjustment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.employee",
                verbose_name="員工",
            ),
        ),
        migrations.AlterField(
            model_name="leavebalanceadjustment",
            name="hours_changed",
            field=models.DecimalField(
                decimal_places=2,
                help_text="輸入正數以增加時數，負數以減少。",
                max_digits=5,
                verbose_name="調整時數",
            ),
        ),
        migrations.AlterField(
            model_name="leavebalanceadjustment",
            name="reason",
            field=models.CharField(max_length=255, verbose_name="調整原因"),
        ),
    ]
