# Generated by Django 5.2.5 on 2025-08-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_leavebalanceadjustment_leave_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavepolicy",
            name="enable_holiday_compensation",
            field=models.BooleanField(
                default=True,
                help_text="如果啟用，當公共假日落在員工的休息日時，系統將自動補償假期。",
                verbose_name="啟用節假日補償",
            ),
        ),
    ]
