# Generated by Django 5.2.5 on 2025-08-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_leavepolicy_enable_holiday_compensation"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="color",
            field=models.CharField(
                default="#888888",
                help_text="請輸入十六進位顏色碼，例如 #FF5733",
                max_length=7,
                verbose_name="部門顏色",
            ),
        ),
    ]
