# Generated by Django 5.2.5 on 2025-08-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_department_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="correspondence_address",
            field=models.TextField(blank=True, verbose_name="通訊地址(如不同)"),
        ),
        migrations.AddField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                blank=True,
                help_text="例如：單身、已婚",
                max_length=20,
                verbose_name="婚姻狀況",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="residential_address",
            field=models.TextField(blank=True, verbose_name="住址"),
        ),
        migrations.AddField(
            model_name="employee",
            name="spouse_id_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="配偶身分證號碼"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="spouse_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="配偶姓名"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="employer_file_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="僱主檔案號碼 (Employer's File No.)",
            ),
        ),
    ]
