# Generated by Django 5.2.5 on 2025-08-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_employee_correspondence_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="公司名稱"),
        ),
    ]
