# Generated by Django 5.2.5 on 2025-08-19 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_siteconfiguration_company_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="compensatory_leave_balance_hours",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="spouse_id_number",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="spouse_name",
        ),
        migrations.AddField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="出生日期"),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="緊急聯絡人姓名"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="緊急聯絡人電話"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("Full-time", "全職"),
                    ("Part-time", "兼職"),
                    ("Contract", "合約"),
                ],
                default="Full-time",
                max_length=20,
                verbose_name="僱傭類型",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="id_number",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="身分證號碼"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="國籍"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="termination_date",
            field=models.DateField(blank=True, null=True, verbose_name="離職日期"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="correspondence_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="core.department",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_number",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "男性"), ("Female", "女性"), ("Other", "其他")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="employee",
            name="leave_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.leavepolicy",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to="core.employee",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Single", "未婚"),
                    ("Married", "已婚"),
                    ("Divorced", "離婚"),
                    ("Widowed", "喪偶"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.position",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="residential_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "在職"),
                    ("On Leave", "休假中"),
                    ("Terminated", "已離職"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="work_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.workschedule",
            ),
        ),
    ]
