# Generated by Django 5.2.5 on 2025-08-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_employee_compensatory_leave_balance_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email_original",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="緊急聯絡Email"
            ),
        ),
    ]
