# Generated by Django 5.2.5 on 2025-08-19 05:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_employee_email_original"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="樣板名稱")),
                ("subject", models.CharField(max_length=255, verbose_name="郵件主旨")),
                (
                    "body",
                    models.TextField(
                        help_text="請使用佔位符來插入動態內容。",
                        verbose_name="郵件內容",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="personal_data_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="通訊地址"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="earliest_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="最早可到職日"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="expected_salary",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="期望薪資",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="linkedin_profile",
            field=models.URLField(
                blank=True, null=True, verbose_name="LinkedIn 個人檔案"
            ),
        ),
    ]
