# Generated by Django 5.2.5 on 2025-08-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_role_employee_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_manager",
            field=models.BooleanField(
                default=False,
                help_text="勾選此項，則擁有此角色的使用者將能看到「團隊管理」等管理員專屬介面。",
                verbose_name="管理權限",
            ),
        ),
    ]
